// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoyViajero.BBDD.Data;

#nullable disable

namespace SoyViajero.BBDD.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220822201427_prueba")]
    partial class prueba
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.Comentario", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CuentasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Publicacion1Id")
                        .HasColumnType("int");

                    b.Property<string>("PublicacionesID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("texto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ID");

                    b.HasIndex("PublicacionesID");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.CuentaHostel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("CuentasHostel");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.CuentaViajero", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("CuentasViajeros");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.fotos_publicacion", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicacionId")
                        .HasColumnType("int");

                    b.Property<string>("PublicacionesID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("PublicacionesID");

                    b.ToTable("fotos_publicaciones");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.Publicacion", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CuentasId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ID");

                    b.ToTable("Publicaciones");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NombreUser" }, "uqUser")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.Comentario", b =>
                {
                    b.HasOne("SoyViajero.BBDD.Data.Entidades.Publicacion", "Publicaciones")
                        .WithMany("Comentarios")
                        .HasForeignKey("PublicacionesID");

                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.CuentaHostel", b =>
                {
                    b.HasOne("SoyViajero.BBDD.Data.Entidades.Usuario", null)
                        .WithMany("cuentasHostel")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.CuentaViajero", b =>
                {
                    b.HasOne("SoyViajero.BBDD.Data.Entidades.Usuario", null)
                        .WithOne("cuentaViajero")
                        .HasForeignKey("SoyViajero.BBDD.Data.Entidades.CuentaViajero", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.fotos_publicacion", b =>
                {
                    b.HasOne("SoyViajero.BBDD.Data.Entidades.Publicacion", "Publicaciones")
                        .WithMany("fotos_publicaciones")
                        .HasForeignKey("PublicacionesID");

                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.Publicacion", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("fotos_publicaciones");
                });

            modelBuilder.Entity("SoyViajero.BBDD.Data.Entidades.Usuario", b =>
                {
                    b.Navigation("cuentaViajero");

                    b.Navigation("cuentasHostel");
                });
#pragma warning restore 612, 618
        }
    }
}
